<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Domain model and ports for Platsbanken job ads (unofficial).</Description>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)../../README.md" Pack="true" PackagePath="/" Visible="false" />
  </ItemGroup>
</Project>
